name: Test & Deploy
on:
  pull_request:
    branches:
    - main

jobs:
  seed_utils:
    name: Test Seed Utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Tests
        run: npm t seedUtils
  
  app_and_utils:
    name: Test App and its Utils
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: testDatabase
          postgresql user: testUser
          postgresql password: testPassword

      - name: Install Dependencies
        run: npm ci

      - name: Set Timezone to Default
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "GMT"
          timezoneMacos: "GMT"
          timezoneWindows: "GMT"

      - name: Run Tests
        run: PGDATABASE=testDatabase PGUSER=testUser PGPASSWORD=testPassword npm t app

