name: Test & Deploy
on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: testDatabase
          postgresql user: testUser
          postgresql password: testPassword

      - name: Install Dependencies
        run: npm ci

      - name: Set Timezone to Default
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "UTC"
          timezoneMacos: "UTC"
          timezoneWindows: "UTC"

      - name: Run Tests
        run: PGDATABASE=testDatabase PGUSER=testUser PGPASSWORD=testPassword npm t

